### ISSUE TITLE
Questionable Database design

### ISSUE THREAD

**Issue by alaireselene** [iCTSV-HUST/ictsv-internal#3]
Thầy @hwangisgone có thể giải thích thêm về các thuộc tính 2 bảng `jsonstorage` và `roles` được không ạ? Em vẫn chưa hiểu lắm các trường có ý nghĩa gì và dùng trong trường hợp nào. Cảm ơn thầy :)

**Comment by hwangisgone** [comment]
@alaireselene 
Bảng `jsonstorage` hiện tại chỉ có thuộc tính `data` để lưu trữ các json. Hiện tại bảng này chỉ được dùng cho cái `wheel-o-fortune`.
Bảng `roles` chứa thông tin về các chức vụ của Tổ:
- `codename`: mã chức vụ (kiểu id)
- `name`: tên chức vụ
- `rank`: cấp độ quyền lực (trên app), với 1 là cao nhất và 6 là thấp nhất
