### ISSUE TITLE
Không truy cập được trang Profile

### ISSUE THREAD

**Issue by alaireselene** [iCTSV-HUST/ictsv-internal#4]
Mô tả: không truy cập được trang Profile qua link `/app/profile`. Trả về lỗi 404.
Tái hiện lỗi: Bấm vào `Profile` trên sidebar
Đề xuất giải quyết: thay đổi thuộc tính `href={null}` và thêm warning badge `Đang phát triển`

**Comment by hwangisgone** [comment]
Done, đã thêm Profile 😉
